---
- name: Gather the package facts
  package_facts:
    manager: auto
- name: Disable firewalld service
  service:
     name: firewalld
     state: stopped
     enabled: no
  when: "'firewalld' in ansible_facts.packages"
- name: Mask Firewalld
  file:
    path: /etc/systemd/system/firewalld.service
    state: link
    src: /dev/null
